singleQuote: true
plugins:
  - prettier-plugin-json-formats
quoteProps: as-needed
trailingComma: all
bracketSpacing: false
arrowParens: avoid

overrides:
  - files: package.json
    options:
      parser: package-json
