singleQuote: true
plugins:
  - ./index.js
quoteProps: as-needed
trailingComma: all
bracketSpacing: false
arrowParens: avoid

overrides:
  - files: package.json
    options:
      parser: package-json
